name: practice-ci-cd
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node2v4
      with:
          node-version: "20"
      - run: |
          echo "Hello, world!"
          pwd
          ls -la
